# Request API Notification

### Create notification
POST http://localhost:3000/notifications HTTP/1.1
content-type: application/json

{
  "category": "social",
  "content": "New member in your chanel",
  "recipientId": "da1f365e-501d-4242-aec6-e50bbcab8d45"
}

### Invalid content when create notification
POST http://localhost:3000/notifications HTTP/1.1
content-type: application/json

{
  "category": "social",
  "content": "you",
  "recipientId": "da1f365e-501d-4242-aec6-e50bbcab8d45"
}

### Invalid recipientId when create notification
POST http://localhost:3000/notifications HTTP/1.1
content-type: application/json

{
  "category": "social",
  "content": "New member in your chanel",
  "recipientId": "invalid_id"
}

### Invalid category when create notification
POST http://localhost:3000/notifications HTTP/1.1
content-type: application/json

{
  "category": "",
  "content": "New member in your chanel",
  "recipientId": "da1f365e-501d-4242-aec6-e50bbcab8d45"
}

### Cancel notification
PATCH http://localhost:3000/notifications/43a3217c-c3a7-408b-ba2f-07a102103c9a/cancel HTTP/1.1

### Read notification
PATCH http://localhost:3000/notifications/43a3217c-c3a7-408b-ba2f-07a102103c9a/read HTTP/1.1

### Unread notification
PATCH http://localhost:3000/notifications/89c7f403-55a5-4d18-9274-112785ca2898/unread HTTP/1.1

### Count notifications to recipient
GET http://localhost:3000/notifications/count/from/da1f365e-501d-4242-aec6-e50bbcab8d45 HTTP/1.1

### Get all notifications active to recipient
GET http://localhost:3000/notifications/from/da1f365e-501d-4242-aec6-e50bbcab8d45 HTTP/1.1
